'use client';
import type { ReactNode } from 'react';
import Footer from '@/components/footer/footer';
import Header from '@/components/header/headerLogo';
import style from './layout.module.scss';
import { creatAiPredictStore } from './aiPredictStore';

function AiPredictPageLayout({ children }: { children: ReactNode }) {
    creatAiPredictStore({
        aiPredictList: [
            {
                matchId: 123,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 124,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 125,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 126,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 127,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 128,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 129,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: 'testest',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 130,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: 'testest',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 131,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 132,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 133,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 134,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            },
            {
                matchId: 135,
                matchTime: 1708509600,
                leagueId: 603,
                leagueEn: 'AUS VPL U21',
                leagueChs: '澳维U21',
                leagueCht: '澳維U21',
                homeEn: 'Heidelberg United U21',
                homeChs: '海德堡联U21',
                homeCht: '海德堡U21',
                awayEn: 'Oakleigh Cannons U21',
                awayChs: '欧克莱卡诺U21',
                awayCht: '歐克萊卡諾U21',
                homeId: 22190,
                awayId: 23426,
                predict: '考虑到波兰女足U19与匈牙利女足U19过去的交锋记录及各自的比赛状态',
                summery:
                    '综观整场比赛，波兰女足U19与匈牙利女足U19都将展示出她们各自的特色与准备，但首先综合双方的',
                homeStrategicAnalysis: 'aaa',
                awayStrategicAnalysis: 'bbb',
                homeTacticalPerspective: 'ccc',
                awayTacticalPerspective: 'ddd',
                updatedAt: 1708509600
            }
        ]
    });

    return (
        <div className={style.aiPredictPageLayout}>
            <Header />
            {children}
            <Footer />
        </div>
    );
}

export default AiPredictPageLayout;
